name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store
  and query firestore documents based on their geographic location with support for cloud_firestore 3.x.x.
version: 3.0.0
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  cloud_firestore: ^3.1.0
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
